language: php
dist: bionic

sudo: required

services:
  - mysql
  - xvfb

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
  - DB=pgsql MOODLE_BRANCH=master
  
before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &
  - wget --max-redirect=1 https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar -O selenium.jar
  - /usr/bin/xvfb-run -s "-screen 0 1280x1024x16" -a java -jar selenium.jar -host localhost -port 4444 &
 
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci add-config '$CFG->behat_profiles = ["firefox" => ["browser" => "firefox", "capabilities" => ["extra_capabilities" => ["marionette" => false, "binary" => "/usr/bin/X11/firefox"]]]];'
  - cat /home/travis/build/moodle/config.php
  - php /home/travis/build/moodle/admin/tool/behat/cli/init.php
  - /home/travis/build/moodle/vendor/bin/phpunit "provider_testcase" /home/travis/build/moodle/privacy/tests/provider_test.php
  - /home/travis/build/moodle/vendor/bin/phpunit "tool_dataprivacy_expired_contexts_testcase" /home/travis/build/moodle/admin/tool/dataprivacy/tests/expired_contexts_test.php
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc || true
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-text --coverage-clover
  - moodle-plugin-ci behat --profile firefox || true
  - moodle-plugin-ci behat --profile chrome

after_success:
  - moodle-plugin-ci coveralls-upload